name: Build & Test
on:
 - push
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl make nasm qemu-user-static \
               gcc-x86-64-linux-gnu binutils-x86-64-linux-gnu \
               gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
          curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Build and Test
        run: |
          . "$HOME/.cargo/env"
          make -s ci_tests

      - name: Public artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build Artifact
          path: out/
