name: Build & Test
on:
  push:
    branches: [ main, rust ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: make -s ci_setup

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifact
          path: out/
